"""
Generates firmware/PocketNova/TvCodes.h from tv_codes.json.

    python gen_tvcodes.py

tv_codes.json is the source of truth for the TV remote. Every code records
where it was confirmed, and only codes with enough evidence go on the device:
  "sources": list of where the code was found (URLs or source names)
A button counts as "verified" when 2+ independent sources agree.

Code format (per button):
  {"proto": "NEC", "bits": 32, "data": "20DF10EF", "sources": [...], "alt": {...same shape...}}
  RC5 / RC6: "data" is the command number and "addr" the address.
  SHARP: "data" is the raw 15-bit frame (as sent by sendSharpRaw).
  PANASONIC: "addr" is the 16-bit address (usually 0x4004) and "data" the 32-bit data.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "tv_codes.json")
OUT = os.path.join(HERE, "..", "PocketNova", "TvCodes.h")

CMDS = ["POWER", "VOL+", "VOL-", "MUTE", "CH+", "CH-", "INPUT"]
PROTOS = {"NEC", "SAMSUNG", "SONY", "PANASONIC", "RC5", "RC6", "JVC", "SHARP", "MITSUBISHI"}
DEFAULT_BITS = {"NEC": 32, "SAMSUNG": 32, "SONY": 12, "PANASONIC": 48, "RC5": 12, "RC6": 20, "JVC": 16, "SHARP": 15, "MITSUBISHI": 16}


def hexval(v):
    if isinstance(v, int):
        return v
    return int(str(v).replace("0x", "").replace("0X", ""), 16)


def code_c(c):
    if not c:
        return "{IR_NONE, 0, 0, 0}"
    proto = c["proto"].upper()
    if proto not in PROTOS:
        raise ValueError(f"unsupported protocol {proto}")
    bits = int(c.get("bits") or DEFAULT_BITS[proto])
    addr = hexval(c.get("addr", 0) or 0)
    data = hexval(c["data"])
    return f"{{IR_{proto}, {bits}, 0x{addr:X}, 0x{data:X}ULL}}"


def verified(c):
    return bool(c) and len(set(c.get("sources", []))) >= 2


def main():
    with open(SRC, encoding="utf-8") as f:
        db = json.load(f)
    brands = db["brands"]
    names = [b["name"] for b in brands]
    lines = [
        "#pragma once",
        "// =====================================================================",
        "//  TvCodes.h - GENERATED by firmware/tools/gen_tvcodes.py",
        "//  from firmware/tools/tv_codes.json. Do not edit by hand.",
        "// =====================================================================",
        "",
        "const TvBrand BRANDS[] = {",
    ]
    for b in brands:
        codes = [b["codes"].get(c) for c in CMDS]
        alts = [(b["codes"].get(c) or {}).get("alt") for c in CMDS]
        nver = sum(1 for c in codes if verified(c))
        r, g, bl = b.get("color", [180, 180, 180])
        lines.append(f'  {{"{b["name"]}", \'{b["letter"]}\', CRGB({r}, {g}, {bl}),')
        lines.append("   {" + ", ".join(code_c(c) for c in codes) + "},")
        lines.append("   {" + ", ".join(code_c(c) for c in alts) + "},")
        lines.append(f"   {nver}}},   // {nver}/{sum(1 for c in codes if c)} buttons confirmed by 2+ sources")
    lines += ["};", "const uint8_t BRAND_COUNT = sizeof(BRANDS) / sizeof(BRANDS[0]);", ""]

    lines.append("// Power codes tried in order by FIND TV (most common TVs first).")
    lines.append("const SweepEntry POWER_SWEEP[] = {")
    def key(c):
        return (c["proto"].upper(), hexval(c.get("addr", 0) or 0), hexval(c["data"])) if c else None
    power_keys = {}
    for i, b in enumerate(brands):
        p = b["codes"].get("POWER")
        for c in (p, (p or {}).get("alt")):
            if c and key(c) not in power_keys:
                power_keys[key(c)] = i
    for s in db.get("sweep", []):
        # a sweep code belongs to a brand when it IS that brand's power code
        bi = names.index(s["brand"]) if s.get("brand") in names else power_keys.get(key(s), -1)
        lines.append(f'  {{{code_c(s)}, {bi}, "{s.get("label", s.get("brand", "?"))}"}},')
    lines += ["};", "const uint16_t SWEEP_COUNT = sizeof(POWER_SWEEP) / sizeof(POWER_SWEEP[0]);", ""]

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT}: {len(brands)} brands, {len(db.get('sweep', []))} power-sweep codes")


if __name__ == "__main__":
    main()
